import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/store/auth";
import ProtectedClient from "@/components/Protected/ProtectedClient";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/themeprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Stockify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ProtectedClient>
              <Toaster />
              <main>  {children}</main>
            </ProtectedClient>
          </ThemeProvider>
        </body>
      </html >
    </AuthProvider >
  );
}
